protected/controllers/PesertaController.php
<?php

class PesertaController extends Controller
{
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    public function accessRules()
    {
        return array(
            array('allow',
                'actions'=>array('login', 'logout', 'error'),
                'users'=>array('*'),
            ),
            array('allow',
                'actions'=>array('aktif', 'error'),
                'users'=>array('@'),
            ),
            array('allow',
                'actions'=>array('admin', 'index', 'nilai', 'sync', 'ubah', 'error'),
                'users'=>array('admin'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    public function actionIndex()
    {
        $this->layout = 'admin';
        $criteria = array(
            'condition' => 'contestant_id > 0',
        );
        $model = Contestant::model()->findAll($criteria);
        $this->render('index',array(
            'model'=>$model
        ));
    }

    public function actionNilai()
    {
        $problem = Problem::model()->findAll();
        $key = array();
        foreach($problem as $prob) $key[$prob->problem_id] = $prob->problem_choice_right;

        $answer = Answer::model()->findall();
        foreach($answer as $ans){
            if($ans->answer_choice != ''){
                if($ans->answer_choice == $key[$ans->problem_id]) $ans->answer_score = 4; else $ans->answer_score = -1;
                $ans->update();
            }
        }

        $this->redirect(array('index'));
    }

    public function actionSync()
    {
        $source = 'http://www.math.itb.ac.id/mcf-mmc/home/sync';

        $jsondata = file_get_contents($source);
        $object = get_object_vars(json_decode($jsondata));
        foreach($object as $obj){
            $obj = get_object_vars($obj);
            $model = Contestant::model()->findByPk($obj['contestant_id']);
            if($model == null){
                $model = new Contestant;
                $model->attributes=$obj;
                $model->contestant_id=$obj['contestant_id'];
                $model->save();
            }
            else if($model->contestant_password != $obj['contestant_password']){
                $model->contestant_password = $obj['contestant_password'];
                $model->update();
            }
        }
        $this->redirect(array('index'));
    }

    public function actionUbah()
    {
        if(isset($_GET['id']) && ($_GET['id'] != null)){
            $model = Contestant::model()->findByPk($_GET['id']);
            if(isset($_POST['Contestant'])){
                $model->attributes=$_POST['Contestant'];
                $model->save();
                $this->redirect(array('index'));
            }
            $this->renderPartial('contestant_form', array(
                'id' => $_GET['id'],
                'model' => $model,
                'problemSet' => ProblemSet::model()->findAll(),
            ));
        }
    }

    public function actionAktif()
    {
        $id = Yii::app()->user->id;
        $model = Contestant::model()->findByPk($id);
        $model->contestant_last_active = time();
        $model->save();
        echo 'OK';
    }

    public function actionError()
    {
        if($error=Yii::app()->errorHandler->error)
        {
            if(Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', $error);
        }
    }
}

protected/views/peserta/contestant_form.php
<?php
$form=$this->beginWidget('CActiveForm', array(
	'action'  => Yii::app()->createUrl('/peserta/ubah/'.$model->contestant_id),
	'htmlOptions' => array(
		'class'   => 'form-horizontal',
		'role'    => 'form',
		'enctype' => 'multipart/form-data',
	),
)); 
?>
<?php echo CHtml::errorSummary($model); ?>
<div class="form-group">
	<?php echo $form->hiddenField($model,'contestant_id'); ?>
</div>
<div class="form-group">
	<?php echo $form->label( $model,'contestant_username', array('class'=>'control-label col-md-3') ); ?>
	<div class="col-md-9 text-input-disabled">
		<?php echo $model->contestant_username; ?>
	</div>
</div>
<div class="form-group">
	<?php echo $form->label( $model,'contestant_team_name', array('class'=>'control-label col-md-3') ); ?>
	<div class="col-md-9 text-input-disabled">
		<?php echo 'Tim '.$model->contestant_team_name; ?>
	</div>
</div>
<div class="form-group">
	<label class="control-label col-md-3">Kumpulan Soal</label>
	<div class="col-md-8">
		<select class="form-control" name="Contestant[problem_set_id]" id="Contestant_problem_set_id">
			<?php foreach($problemSet as $ps){ ?>
			<option value="<?php echo $ps->problem_set_id; ?>"<?php echo ($ps->problem_set_id==$model->problem_set_id)?' selected':''; ?>><?php echo $ps->problem_set_name; ?></option>
			<?php } ?>
		</select>
	</div>
</div>
<?php $this->endWidget(); ?>

protected/views/peserta/index.php
<script type="text/javascript">
	function edit(id){
		$.ajax({
			url: "<?php echo Yii::app()->createUrl('/peserta/ubah'); ?>" + "/" + id,
			cache: false
		})
		.done(function(result) {
			$('#dialog-contestant .modal-body').html(result);
			$('#dialog-contestant').modal('show');
		});
	};
</script>

<div class="panel panel-primary">
	<div class="panel-heading admin-main-header"><h4>Peserta</h4></div>
	<div class="panel-body admin-main-body">
		<a href="<?php echo Yii::app()->createUrl('/peserta/sync'); ?>">
			<button type="button" id="toggle-sync-button" class="btn btn-labeled btn-primary">
				<span class="btn-label"><i class="glyphicon glyphicon-refresh"></i></span>
				Sinkronisasi
			</button>
		</a>
		<?php if(time() > Yii::app()->params['contest_end']) { ?>
		<a href="<?php echo Yii::app()->createUrl('/peserta/nilai'); ?>">
			<button type="button" id="toggle-grade-button" class="btn btn-labeled btn-success">
				<span class="btn-label"><i class="glyphicon glyphicon-pencil"></i></span>
				Nilai Semua
			</button>
		</a>
		<?php } ?>
		<table class="table table-striped table-bordered table-hover table-contestant">
			<thead>
				<tr><th style="width: 40px;">No</th><th>Username</th><th>Nama Tim</th><th style="width: 130px;">Kumpulan Soal</th><th style="width: 50px;">Nilai</th></tr>
			</thead>
			<tbody data-link="row" class="rowlink">
			<?php
				$i = 0;
				foreach($model as $mdl){
					++$i;
					$elmt = '<td style="text-align: right; padding-right: 10px;">'.$i.'</td>';
					$elmt .= '<td><a onclick="edit('.$mdl->contestant_id.')">'.$mdl->contestant_username.'</a></td>';
					$elmt .= '<td>Tim '.$mdl->contestant_team_name.'</td>';

					$problemSet = ProblemSet::model()->findByPk($mdl->problem_set_id);
					$problemSet = ($problemSet != null)?$problemSet->problem_set_name:'';
					$elmt .= '<td>'.$problemSet.'</td>';

					$score = Yii::app()->db->createCommand('SELECT SUM(answer_score) as score FROM `answer` WHERE contestant_id = '. $mdl->contestant_id)->queryAll();
					$elmt .= '<td style="text-align: right; padding-right: 20px;">'.$score[0]['score'].'</td>';
					echo '<tr>'.$elmt.'</tr>';
				}
			?>
			</tbody>
	</table>
	</div>
</div>

<div id="dialog-contestant" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Ubah Peserta</h4>
      </div>
      <div class="modal-body"></div>
      <div class="modal-footer">
        <button type="button" id="submit-edit-button" class="btn btn-primary">Ubah</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
	$('#submit-edit-button').click(function(){
		$('form').submit();
	});
</script>