protected/controllers/PesertaController.php
<?php

class PesertaController extends Controller
{
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    public function accessRules()
    {
        return array(
            array('allow',
                'actions'=>array('login', 'logout', 'error'),
                'users'=>array('*'),
            ),
            array('allow',
                'actions'=>array('aktif', 'error'),
                'users'=>array('@'),
            ),
            array('allow',
                'actions'=>array('admin', 'index', 'nilai', 'sync', 'ubah', 'error'),
                'users'=>array('admin'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    public function actionIndex()
    {
        $this->layout = 'admin';
        $criteria = array(
            'condition' => 'contestant_id > 0',
        );
        $model = Contestant::model()->findAll($criteria);
        $this->render('index',array(
            'model'=>$model
        ));
    }

    public function actionNilai()
    {
        $problem = Problem::model()->findAll();
        $key = array();
        foreach($problem as $prob) $key[$prob->problem_id] = $prob->problem_choice_right;

        $answer = Answer::model()->findall();
        foreach($answer as $ans){
            if($ans->answer_choice != ''){
                if($ans->answer_choice == $key[$ans->problem_id]) $ans->answer_score = 4; else $ans->answer_score = -1;
                $ans->update();
            }
        }

        $this->redirect(array('index'));
    }

    public function actionSync()
    {
        $source = 'http://www.math.itb.ac.id/mcf-mmc/home/sync';

        $jsondata = file_get_contents($source);
        $object = get_object_vars(json_decode($jsondata));
        foreach($object as $obj){
            $obj = get_object_vars($obj);
            $model = Contestant::model()->findByPk($obj['contestant_id']);
            if($model == null){
                $model = new Contestant;
                $model->attributes=$obj;
                $model->contestant_id=$obj['contestant_id'];
                $model->save();
            }
            else if($model->contestant_password != $obj['contestant_password']){
                $model->contestant_password = $obj['contestant_password'];
                $model->update();
            }
        }
        $this->redirect(array('index'));
    }

    public function actionUbah()
    {
        if(isset($_GET['id']) && ($_GET['id'] != null)){
            $model = Contestant::model()->findByPk($_GET['id']);
            if(isset($_POST['Contestant'])){
                $model->attributes=$_POST['Contestant'];
                $model->save();
                $this->redirect(array('index'));
            }
            $this->renderPartial('contestant_form', array(
                'id' => $_GET['id'],
                'model' => $model,
                'problemSet' => ProblemSet::model()->findAll(),
            ));
        }
    }

    public function actionAktif()
    {
        $id = Yii::app()->user->id;
        $model = Contestant::model()->findByPk($id);
        $model->contestant_last_active = time();
        $model->save();
        echo 'OK';
    }

    public function actionError()
    {
        if($error=Yii::app()->errorHandler->error)
        {
            if(Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', $error);
        }
    }
}

protected/controllers/TesController.php
<?php

class TesController extends Controller
{
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    public function accessRules()
    {
        return array(
            array('allow',
                'actions'=>array('index', 'cek', 'login', 'logout', 'error'),
                'users'=>array('*'),
            ),
            array('allow',
                'actions'=>array('index', 'kumpul', 'pra', 'error'),
                'users'=>array('@'),
            ),
            array('allow',
                'actions'=>array('admin', 'index', 'error'),
                'users'=>array('admin'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    public function actionCek()
    {
        if(isset($_GET['username']) && ($_GET['username'] != null)){
            $model = Contestant::model()->findByAttributes(array('contestant_username' => $_GET['username']));
            if($model == null) echo 'not found'; else echo 'ok';
        }
    }

    public function actionLogin()
    {
        $model = new Contestant;

        if(isset($_POST['Contestant']))
        {
            $model->attributes          = $_POST['Contestant'];
            $password                   = $model->contestant_password;
            $user                       = new UserIdentity('admin', '');
            $model->contestant_password = $user->encrypt($password);
            $model->problem_set_id      = Yii::app()->params['test_problem_set'];
            if(Contestant::model()->findByAttributes(array('contestant_username' => $model->contestant_username)) == null) $model->save();

            $user = new LoginForm;
            $user->username = $model->contestant_username;
            $user->password = $password;
            if($user->validate() && $user->login()){
                if (Yii::app()->user->id == 0) $this->redirect(array("site/admin"));
                else if((time() >= Yii::app()->params['contest_start'])) $this->redirect(array("index"));
                else $this->redirect(array("site/logout"));
            }
        }

        $this->render('login',array('model'=>$model));
    }

    public function actionPra()
    {
        $userModel = Contestant::model()->findByPk(Yii::app()->user->id);
        $userModel->contestant_start_time = $userModel->contestant_last_active = $userModel->contestant_last_submit = time();
        $userModel->save();
        $this->redirect(array('tes/index?new=true'));
    }

    public function actionIndex()
    {
        if(Yii::app()->user->isGuest) $this->redirect(array('tes/login'));

        $userModel = Contestant::model()->findByPk(Yii::app()->user->id);

        if($userModel->contestant_start_time == null){
            if(time() < Yii::app()->params['contest_end']) $this->render('preliminary');
            else $this->render('end');
        }
        else{
            $userModel->contestant_last_active = time();
            $userModel->save();

            //new login
            if($userModel->contestant_problem_worked == null){
                $this->generateProblem(0, $userModel);
                $userModel = Contestant::model()->findByPk(Yii::app()->user->id);
            }

            $worked = json_decode($userModel->contestant_problem_worked);

            //past time limit
            $i=1;
            while($userModel->contestant_last_submit + ($i * Yii::app()->params['section_duration']) <= time()) ++$i;
            if($i > 1){
                $userModel->contestant_last_submit += ($i - 1) * Yii::app()->params['section_duration'];
                $userModel->save();
                $this->generateProblem($worked->section + $i - 1, $userModel);
                $userModel = Contestant::model()->findByPk(Yii::app()->user->id);
                $worked = json_decode($userModel->contestant_problem_worked);
            }

            $contestEnd = Yii::app()->params['section_duration'] * (Yii::app()->params['total_section'] - $worked->section) + $userModel->contestant_last_submit;
            if(($worked->section >= Yii::app()->params['total_section']) || (sizeof($worked->problem) == 0)) $this->render('end');
            else{
                $problem = array();
                foreach($worked->problem as $id){
                    $model = Problem::model()->findByPk($id);
                    array_push($problem, $model);
                }

                $this->render('index', array(
                    'start'       => $worked->section * Yii::app()->params['problem_per_section'] + 1,
                    'problem'     => $problem,
                    'timeLeft'    => $contestEnd - time(),
                    'submitTimer' => $userModel->contestant_last_submit + Yii::app()->params['section_duration'] - time(),
                ));
            }
        }
    }

    public function actionKumpul()
    {
        if(isset($_POST['Answer'])){
            foreach($_POST['Answer'] as $answer){
                $model = new Answer;
                $model->attributes = $answer;

                $criteria = array(
                    'condition' => 'problem_id = '.$model->problem_id.' AND contestant_id = '.$model->contestant_id,
                );
                $modelOld = Answer::model()->find($criteria);

                if($modelOld == null) $model->save();
                else{
                    $modelOld->attributes = $answer;
                    $modelOld->update();
                }
            }
            if(isset($_GET['new'])){
                $user = Contestant::model()->findByPk(Yii::app()->user->id);
                $user->contestant_last_submit = time();
                $user->save();
                $used = json_decode($user->contestant_problem_worked);
                $this->generateProblem($used->section + 1, $user);
            }
            $this->redirect('index');
        }
    }

    public function actionLogout()
    {
        if(!Yii::app()->user->isGuest){
            $userModel = Contestant::model()->findByPk(Yii::app()->user->id);
            $userModel->contestant_is_login = 0;
            $userModel->save();
            Yii::app()->user->logout();
        }
        $this->redirect('login');
    }

    public function actionError()
    {
        if($error=Yii::app()->errorHandler->error)
        {
            if(Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', $error);
        }
    }

    private function generateProblem($section, $user)
    {
        if($user->contestant_problem_used == null) $used = array();
        else $used = json_decode($user->contestant_problem_used);

        $source = array();
        $criteria = array(
            'condition' => 'problem_set_id = '.$user->problem_set_id,
        );
        $problem = Problem::model()->findAll($criteria);
        foreach($problem as $prob)
            if(!in_array($prob->problem_id, $used)) array_push($source, $prob->problem_id);

        $worked = array();
        while((sizeof($worked) < Yii::app()->params['problem_per_section']) && (sizeof($source) > 0)){
            $end = sizeof($source)-1;
            $idx = mt_rand(0, $end);
            $temp         = $source[$idx];
            $source[$idx] = $source[$end];
            array_pop($source);
            array_push($worked, $temp);
            array_push($used, $temp);
        }

        $result = array(
            'section' => $section,
            'problem' => $worked,
        );

        $user->contestant_problem_worked = json_encode($result);
        $user->contestant_problem_used = json_encode($used);
        $user->save();
    }
}

protected/views/tes/end.php
<div style="width: 800px; margin: 200px auto 0;">
	<div style="width: 600px; margin: 0 auto 20px;"><h3>Tes telah selesai, terima kasih atas partisipasinya ^^</h3></div>
	<div style="width: 700px; margin: 0 auto 50px;">
		<h4>Jika ada kesalahan dalam sistem ini mohon beritahukan kami melalui tautan <a target="_blank" href="http://www.math.itb.ac.id/mcf-mmc/feedback">berikut</a></h4>
	</div>
	<a href="<?php echo Yii::app()->createUrl("/tes/logout"); ?>" style="margin-left:325px;">
		<button type="button" class="btn btn-labeled btn-danger">
			<span class="btn-label"><i class="glyphicon glyphicon-off"></i></span>
			Keluar
		</button>
	</a>
</div>

protected/views/tes/index.php
<div id="preliminary-nav">
	<div id="preliminary-nav-inner">
		<div id="preliminary-nav-logo">
			<img src="<?php echo Yii::app()->request->baseUrl; ?>/img/Untitled-21.png" alt="MCF-MMC 2014" title="Babak Penyisihan">
		</div>
		<div id="preliminary-nav-timer"></div>
		<nav id="preliminary-nav-menu">
			<ul>
				<li id="preliminary-nav-menu-save"><a title="Simpan"><i class="glyphicon glyphicon-floppy-disk"></i></a></li>
				<li id="preliminary-nav-menu-submit"><a title="Kumpulkan"><i class="glyphicon glyphicon-ok"></i></a></li>
				<li><a title="Keluar" href="<?php echo Yii::app()->createUrl("/tes/logout"); ?>"><i class="glyphicon glyphicon-off"></i></a></li>
			</ul>
		</nav>
	</div>
</div>
<?php
$i = 0;
$form=$this->beginWidget('CActiveForm', array(
	'id' => 'preliminary-form',
	'htmlOptions' => array(
		'class'   => 'form-horizontal',
		'role'    => 'form',
		'enctype' => 'multipart/form-data',
	)
));
?>

<?php
foreach($problem as $prob) {
	$criteria = array(
		'condition' => 'problem_id = '.$prob->problem_id.' AND contestant_id = '.Yii::app()->user->id,
	);
	$answer = Answer::model()->find($criteria);
	$choice = ($answer == null)?'':$answer->answer_choice;
?>
<div class="preliminary-form-group">
	<div class="preliminary-form-numbering"><?php echo ($start+$i).')'; ?></div>
	<div class="preliminary-form-content">
		<div class="preliminary-form-problem"><?php echo $prob->problem_description?></div>
		<div class="preliminary-form-answer">
			<div class="preliminary-form-choice">
				<input type="radio" name="Answer[<?php echo $i; ?>][answer_choice]" value="A"<?php echo ($choice == 'A')?' checked':'';?>> A. <?php echo $prob->problem_choice_a; ?>
			</div>
			<div class="preliminary-form-choice">
				<input type="radio" name="Answer[<?php echo $i; ?>][answer_choice]" value="B"<?php echo ($choice == 'B')?' checked':'';?>> B. <?php echo $prob->problem_choice_b; ?>
			</div>
			<div class="preliminary-form-choice">
				<input type="radio" name="Answer[<?php echo $i; ?>][answer_choice]" value="C"<?php echo ($choice == 'C')?' checked':'';?>> C. <?php echo $prob->problem_choice_c; ?>
			</div>
			<div class="preliminary-form-choice">
				<input type="radio" name="Answer[<?php echo $i; ?>][answer_choice]" value="D"<?php echo ($choice == 'D')?' checked':'';?>> D. <?php echo $prob->problem_choice_d; ?>
			</div>
			<div class="preliminary-form-choice">
				<input type="radio" name="Answer[<?php echo $i; ?>][answer_choice]" value="E"<?php echo ($choice == 'E')?' checked':'';?>> E. <?php echo $prob->problem_choice_e; ?>
			</div>
		</div>
		<input type="hidden" name="Answer[<?php echo $i; ?>][contestant_id]" value="<?php echo Yii::app()->user->id; ?>">
		<input type="hidden" name="Answer[<?php echo $i; ?>][problem_id]" value="<?php echo $prob->problem_id; ?>">
	</div>
</div>
<?php ++$i; } ?>

<?php $this->endWidget(); ?>

<?php if(isset($_GET['new'])){?>
<div id="pre-dialog" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Jangan lupa</h4>
      </div>
      <div class="modal-body">Anda hanya diberikan waktu mengerjakan maksimal <?php echo round(Yii::app()->params['section_duration']/60,2).' menit'; ?> per sesinya</div>
      <div class="modal-footer">
        <button type="button"class="btn btn-primary" data-dismiss="modal" aria-hidden="true">OK</button>
      </div>
    </div>
  </div>
</div>
<script language="javascript" type="text/javascript">
	$('#pre-dialog').modal('show');
</script>
<?php } ?>

<script language="javascript" type="text/javascript">
	$('#preliminary-nav-menu-save').click(function(){
		$('form').attr('action', '<?php echo Yii::app()->createUrl('/tes/kumpul'); ?>');
		$('form').submit();
	});

	function submit(){
		$('form').attr('action', '<?php echo Yii::app()->createUrl('/tes/kumpul?new=true'); ?>');
		$('form').submit();
	}
	
	$('#preliminary-nav-menu-submit').click(function(){
		submit();
	});

	//active report
	activeReff = <?php echo Yii::app()->params['active_interval'];?>;
	interval = activeReff;
	
	function active(){
		$.ajax({
			url: "<?php echo Yii::app()->createUrl('/peserta/aktif'); ?>",
			cache: false
		})
		.done(function(result) {
			interval = activeReff;
		});
	}
	
	//timer
	timeLeft = <?php echo $timeLeft; ?>;
	submitTimer = <?php echo $submitTimer; ?>;

	function formatTime(){
		time = timeLeft;
		seconds = (time%60).toString();
		while(seconds.length < 2) seconds = '0' + seconds;
		time = parseInt(time/60);
		minutes = (time%60).toString();
		while(minutes.length < 2) minutes = '0' + minutes;
		time = parseInt(time/60);
		hours = (time%60).toString();
		while(hours.length < 2) hours = '0' + hours;
		$('#preliminary-nav-timer').html(hours+' : '+minutes+' : '+seconds);
	}

	countDown = setInterval(function() {
		//timer
		if(timeLeft > 0){
			--timeLeft;
			formatTime();
		}
		else{
			clearInterval(countDown);
			return;
		}

		//auto submit
		if(submitTimer > 0) --submitTimer;
		if(submitTimer == 0){
			submit();
			clearInterval(countDown);
			return;
		}

		//active report
		if(interval > 0) --interval;
		if(interval == 0) active();
	}, 1000);
</script>

protected/views/tes/login.php
<div id="login-panel" class="panel panel-danger">
	<div class="panel-heading"><h4>Tes Login</h4></div>
	<div class="panel-body">
		<form action="<?php echo Yii::app()->createUrl("tes/login"); ?>" method="post" role="form">
			<div class="form-group">
				<label class="sr-only" for="inputUsername">Username</label>
				<input type="text" class="form-control" id="Contestant_contestant_username" name="Contestant[contestant_username]" placeholder="Username">
			</div>
			<div class="form-group">
				<label class="sr-only" for="inputPassword">Password</label>
				<input type="password" class="form-control" id="Contestant_contestant_password" name="Contestant[contestant_password]" placeholder="Password">
			</div>
			<div class="form-group">
				<label class="sr-only" for="inputName">Nama</label>
				<input type="text" class="form-control" id="Contestant_contestant_team_name" name="Contestant[contestant_team_name]" placeholder="Nama" style="display: none;">
			</div>
			<div style="width: 60px; position:relative; margin: 0 auto;"><input class="btn btn-default btn-sm" type="submit" value="Masuk"></div>
		</form>
	</div>
</div>

<div id="dialog-error" class="modal fade">
  <div class="modal-dialog" style="width: 200px">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>
      <div class="modal-body"></div>
    </div>
  </div>
</div>

<script type="text/javascript">
	$('#Contestant_contestant_password').focus(function(){
		if($('#Contestant_contestant_username').val() == ''){
			$('#Contestant_contestant_username').focus();
		}
		else{
			$.ajax({
				url: "<?php echo Yii::app()->createUrl('/tes/cek') ?>" + "?username=" + $('#Contestant_contestant_username').val(),
				cache: false
			})
			.done(function(result){
				if(result == 'ok'){
					$('#Contestant_contestant_team_name').hide();
					$('.panel-heading').html('<h4>Tes Login</h4>');
					$('#submit-button').val('Masuk');
				}
				else if(result == 'not found'){
					$('#Contestant_contestant_team_name').show();
					$('.panel-heading').html('<h4>Tes Daftar & Login</h4>');
					$('#submit-button').val('Daftar');
				}
			});
		}
	});

	$('#Contestant_contestant_username').focus(function(){
		$(this).removeClass('error-input');
	});
</script>

protected/views/tes/preliminary.php
<div style="width: 500px; margin: 225px auto 0;">
	<div  style="font-size: 20px;">Apakah Anda yakin untuk memasuki sistem penyisihan?</div>
	<div>
		<div>
			<strong>Anda hanya diberikan waktu <?php echo round(Yii::app()->params['total_section']*Yii::app()->params['section_duration']/3600, 2).' jam'; ?> untuk mengerjakan terhitung dari</strong>
		</div>
		<div><strong>Anda menekan tombol Lanjutkan</strong></div>
	</div>
	<div style="margin-top: 50px;">
		<a href="<?php echo Yii::app()->createUrl("/tes/logout"); ?>" style="margin-left: 30px;"><button class="btn btn-danger" style="width: 100px;">Batal</button></a>
		<a href="<?php echo Yii::app()->createUrl("/tes/pra"); ?>" style="margin-left: 200px;"><button class="btn btn-success" style="width: 100px;">Lanjutkan</button></a>
	</div>
</div>